services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - db:/var/lib/postgresql/data

  backend:
    image: nicolaspaillard/bdobackend:latest
    restart: always
    environment:
      LOG_LEVEL: info
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      PORT: 8081
      GIN_MODE: release
    ports:
      - 8081:8081
    depends_on:
      - db

  backend-dev:
    image: nicolaspaillard/bdobackend-dev:latest
    restart: always
    environment:
      LOG_LEVEL: info
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      PORT: 8081
      GIN_MODE: release
    ports:
      - 8081:8081
    volumes:
      - backend:/app
    depends_on:
      - db

  api:
    image: nicolaspaillard/bdoapi:latest
    restart: always
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      PORT: 8080
      NODE_ENV: production
    ports:
      - 8080:8080
    depends_on:
      - db

  api-nest:
    image: bdoapi/api-nest:latest
    restart: always
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      PORT: 3000
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  db:
  backend:
